### ISSUE TITLE
HW: Hub data collection, parsing, and routing

### ISSUE THREAD

**Issue by ghost** [Plantalytics/plantalytics-hardware#12]
- [ ] Create script to continuously gather & save data from nodes
- [ ] Create script that grabs the data batch every 5 minutes, parses it, saves a local backup, and sends it off to the database

**Comment by kbrimm** [comment]
Issue moved to [Plantalytics/plantalytics-hub #7](https://github.com/Plantalytics/plantalytics-hub/issues/7) via [**ZenHub**](https://www.zenhub.com/)
