### ISSUE TITLE
HW: Node data collection 08/03

### ISSUE THREAD

**Issue by kbrimm** [Plantalytics/plantalytics-hardware#8]
Nodes gather data during "wake-ups" and transfer data to the hub.
- [ ] Nodes gather sensor data
- [ ] Nodes generate data packet
- [ ] Nodes transfer data to hub

**Comment by SoySauceLabs** [comment]
I'm thinking Steven can determine if this is still a valid issue.

**Comment by kbrimm** [comment]
If I recall correctly, this is kind of almost there in bits and pieces, but needs to be solidified. Tentative due date of 8/3 to allow us a couple work days for collaboration.

**Comment by kbrimm** [comment]
Blocked on hardware error.
